import { IMAGE_MAP as I } from './imageMap.js';

export const MOCK_COMPANIES = [
  { id: 1,  name: "뤼이드",             img: I.뤼이드,           category: "에듀테크",     description: "AI 기반 적응형 학습 솔루션을 개발하는 에듀테크 스타트업입니다.",          myCount: 9804, compareCount: 3201 },
  { id: 2,  name: "매스프레소",          img: I.매스프레소,        category: "에듀테크",     description: "수학 문제 풀이 AI 앱 '콴다'를 운영하는 에듀테크 스타트업입니다.",         myCount: 8766, compareCount: 4108 },
  { id: 3,  name: "코드잇",             img: I.코드잇,            category: "에듀테크",     description: "온라인 코딩 교육 서비스를 운영하는 에듀테크 스타트업입니다.",              myCount: 8142, compareCount: 7506 },
  { id: 4,  name: "엘리스",             img: I.엘리스,            category: "에듀테크",     description: "AI 기반 교육 플랫폼을 운영하는 에듀테크 스타트업입니다.",                  myCount: 7204, compareCount: 9224 },
  { id: 5,  name: "아이헤이트플라잉버드", img: I.밀당PT,            category: "헬스테크",     description: "1:1 퍼스널 트레이닝 매칭 플랫폼을 운영하는 헬스테크 스타트업입니다.",     myCount: 5763, compareCount: 5763 },
  { id: 6,  name: "클래스101",          img: I.클래스101,         category: "에듀테크",     description: "크리에이터와 학습자를 연결하는 온라인 클래스 플랫폼입니다.",               myCount: 4004, compareCount: 5883 },
  { id: 7,  name: "스파르타코딩클럽",    img: I.스파르타코딩클럽,   category: "에듀테크",     description: "비개발자를 위한 코딩 교육 서비스를 운영하는 에듀테크 스타트업입니다.",     myCount: 3951, compareCount: 504  },
  { id: 8,  name: "채널톡",             img: I.채널톡,            category: "SaaS",        description: "B2B 고객 커뮤니케이션 플랫폼을 운영하는 스타트업입니다.",                   myCount: 1768, compareCount: 2375 },
  { id: 9,  name: "탈잉",               img: I.탈잉,              category: "에듀테크",     description: "재능 공유 플랫폼을 운영하는 스타트업입니다.",                              myCount: 941,  compareCount: 1481 },
  { id: 10, name: "토스",               img: I.토스,              category: "핀테크",       description: "간편 송금 서비스를 시작으로 종합 금융 플랫폼으로 성장한 핀테크 스타트업입니다.", myCount: 867, compareCount: 675 },
  { id: 11, name: "뱅크샐러드",          img: I.뱅크샐러드,        category: "핀테크",       description: "개인 자산 관리 서비스를 제공하는 핀테크 스타트업입니다.",                  myCount: 754,  compareCount: 1203 },
  { id: 12, name: "카카오페이",          img: I.카카오페이,        category: "핀테크",       description: "카카오 기반 간편 결제 및 금융 서비스를 운영하는 핀테크 기업입니다.",       myCount: 623,  compareCount: 879  },
  { id: 13, name: "마켓컬리",            img: I.마켓컬리,          category: "커머스",       description: "새벽 배송 서비스를 운영하는 커머스 스타트업입니다.",                       myCount: 512,  compareCount: 634  },
  { id: 14, name: "오늘의집",            img: I.오늘의집,          category: "라이프스타일", description: "인테리어 커머스 및 커뮤니티 플랫폼을 운영하는 스타트업입니다.",            myCount: 438,  compareCount: 521  },
  { id: 15, name: "당근마켓",            img: I.당근마켓,          category: "로컬커머스",   description: "지역 기반 중고 거래 플랫폼을 운영하는 스타트업입니다.",                    myCount: 321,  compareCount: 445  },
  { id: 16, name: "야놀자",              img: I.야놀자,            category: "여행/숙박",    description: "숙박 및 여행 플랫폼을 운영하는 여행테크 스타트업입니다.",                  myCount: 289,  compareCount: 367  },
  { id: 17, name: "직방",               img: I.직방,              category: "프롭테크",     description: "부동산 정보 플랫폼을 운영하는 프롭테크 스타트업입니다.",                   myCount: 201,  compareCount: 298  },
  { id: 18, name: "무신사",              img: I.무신사,            category: "패션",         description: "패션 커머스 플랫폼을 운영하는 스타트업입니다.",                            myCount: 178,  compareCount: 234  },
  { id: 19, name: "닥터다이어리",        img: I.닥터다이어리,       category: "헬스케어",     description: "당뇨 환자를 위한 건강 관리 플랫폼을 운영하는 헬스케어 스타트업입니다.",   myCount: 134,  compareCount: 189  },
  { id: 20, name: "눔",                  img: I.눔,                category: "헬스테크",     description: "심리학 기반 체중 감량 앱을 운영하는 헬스테크 스타트업입니다.",             myCount: 98,   compareCount: 145  },
  { id: 21, name: "크래프톤",            img: I.크래프톤,          category: "게임",         description: "배틀그라운드를 개발한 글로벌 게임 스타트업입니다.",                        myCount: 87,   compareCount: 132  },
  { id: 22, name: "하이퍼커넥트",        img: null,               category: "소셜",         description: "영상 기반 소셜 미디어 플랫폼 '아자르'를 운영하는 스타트업입니다.",        myCount: 76,   compareCount: 98   },
  { id: 23, name: "버킷플레이스",        img: I.오늘의집,          category: "라이프스타일", description: "홈 인테리어 플랫폼 '오늘의집'을 운영하는 스타트업입니다.",                myCount: 65,   compareCount: 87   },
  { id: 24, name: "두나무",              img: I.두나무,            category: "핀테크",       description: "암호화폐 거래소 '업비트'를 운영하는 핀테크 스타트업입니다.",              myCount: 54,   compareCount: 76   },
  { id: 25, name: "비바리퍼블리카",      img: I.토스,              category: "핀테크",       description: "간편 금융 서비스 '토스'를 운영하는 핀테크 스타트업입니다.",              myCount: 43,   compareCount: 65   },
  { id: 26, name: "컬리",               img: I.마켓컬리,          category: "커머스",       description: "신선식품 새벽배송 서비스를 운영하는 커머스 스타트업입니다.",               myCount: 39,   compareCount: 54   },
  { id: 27, name: "원티드랩",            img: I.원티드랩,          category: "HR테크",      description: "AI 기반 채용 플랫폼을 운영하는 HR테크 스타트업입니다.",                   myCount: 34,   compareCount: 48   },
  { id: 28, name: "리멤버",              img: I.리멤버,            category: "HR테크",      description: "명함 관리 및 비즈니스 네트워킹 플랫폼을 운영하는 스타트업입니다.",        myCount: 28,   compareCount: 41   },
  { id: 29, name: "카닥",               img: I.카닥,              category: "오토테크",     description: "자동차 수리 견적 비교 플랫폼을 운영하는 오토테크 스타트업입니다.",         myCount: 23,   compareCount: 35   },
  { id: 30, name: "쏘카",               img: I.쏘카,              category: "모빌리티",     description: "카셰어링 서비스를 운영하는 모빌리티 스타트업입니다.",                      myCount: 19,   compareCount: 28   },
  { id: 31, name: "타다",               img: I.타다,              category: "모빌리티",     description: "혁신적인 모빌리티 서비스를 운영하는 스타트업입니다.",                      myCount: 16,   compareCount: 22   },
  { id: 32, name: "플렉스",              img: I.플렉스,            category: "HR테크",      description: "HR SaaS 플랫폼을 운영하는 스타트업입니다.",                               myCount: 14,   compareCount: 19   },
  { id: 33, name: "센드버드",            img: I.센드버드,          category: "SaaS",        description: "채팅 API 및 인앱 메시징 플랫폼을 제공하는 B2B 스타트업입니다.",           myCount: 11,   compareCount: 16   },
  { id: 34, name: "몰로코",              img: I.몰로코,            category: "애드테크",     description: "머신러닝 기반 광고 플랫폼을 운영하는 애드테크 스타트업입니다.",           myCount: 9,    compareCount: 13   },
  { id: 35, name: "에이블리",            img: I.에이블리,          category: "패션",         description: "AI 기반 여성 패션 커머스 플랫폼을 운영하는 스타트업입니다.",              myCount: 7,    compareCount: 11   },
  { id: 36, name: "지그재그",            img: I.지그재그,          category: "패션",         description: "여성 패션 쇼핑 앱을 운영하는 커머스 스타트업입니다.",                      myCount: 6,    compareCount: 9    },
  { id: 37, name: "브랜디",              img: I.브랜디,            category: "패션",         description: "패션 커머스 및 풀필먼트 서비스를 운영하는 스타트업입니다.",               myCount: 5,    compareCount: 7    },
  { id: 38, name: "식스샵",              img: I.식스샵,            category: "커머스",       description: "소상공인을 위한 온라인 쇼핑몰 창업 플랫폼을 운영하는 스타트업입니다.",    myCount: 4,    compareCount: 6    },
  { id: 39, name: "리디",               img: I.리디,              category: "콘텐츠",       description: "전자책 및 웹툰 플랫폼을 운영하는 콘텐츠 스타트업입니다.",                 myCount: 3,    compareCount: 5    },
  { id: 40, name: "왓챠",               img: I.왓챠,              category: "콘텐츠",       description: "OTT 스트리밍 서비스를 운영하는 콘텐츠 스타트업입니다.",                   myCount: 2,    compareCount: 3    },
  { id: 41, name: "노트폴리오",          img: I.노트폴리오,        category: "크리에이터",   description: "크리에이터를 위한 포트폴리오 및 커뮤니티 플랫폼입니다.",                  myCount: 2,    compareCount: 2    },
  { id: 42, name: "점핏",               img: I.점핏,              category: "HR테크",      description: "개발자 특화 채용 플랫폼을 운영하는 HR테크 스타트업입니다.",               myCount: 1,    compareCount: 2    },
  { id: 43, name: "클래스유",            img: I.클래스유,          category: "에듀테크",     description: "성인 교육 및 자기계발 온라인 플랫폼을 운영하는 에듀테크 스타트업입니다.", myCount: 1,    compareCount: 1    },
  { id: 44, name: "패스트파이브",        img: I.패스트파이브,       category: "프롭테크",     description: "공유 오피스 서비스를 운영하는 프롭테크 스타트업입니다.",                  myCount: 1,    compareCount: 1    },
  { id: 45, name: "스푼라디오",          img: I.스푼,              category: "미디어",       description: "오디오 스트리밍 및 라이브 방송 플랫폼을 운영하는 스타트업입니다.",        myCount: 1,    compareCount: 1    },
  { id: 46, name: "오피지지",            img: I.OPGG,              category: "게임",         description: "게임 전적 검색 및 분석 서비스를 운영하는 게임테크 스타트업입니다.",       myCount: 1,    compareCount: 1    },
  { id: 47, name: "아이디어스",          img: I.아이디어스,        category: "커머스",       description: "핸드메이드 작품 거래 플랫폼을 운영하는 스타트업입니다.",                  myCount: 1,    compareCount: 1    },
  { id: 48, name: "트레바리",            img: I.트레바리,          category: "소셜",         description: "독서 모임 플랫폼을 운영하는 소셜 스타트업입니다.",                        myCount: 1,    compareCount: 1    },
  { id: 49, name: "퍼블리",              img: I.퍼블리,            category: "콘텐츠",       description: "직장인을 위한 콘텐츠 구독 서비스를 운영하는 스타트업입니다.",             myCount: 1,    compareCount: 1    },
  { id: 50, name: "무신사(2기)",         img: I.무신사,            category: "패션",         description: "글로벌 시장으로 확장 중인 무신사 스토어입니다.",                          myCount: 1,    compareCount: 1    },
];
